version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/go:1.21.6-node

jobs:
  security_scans:
    <<: *defaults
    steps:
      - checkout
      - prodsec/security_scans:
          mode: auto

  build_crawler:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          command: docker build . -f gh_crawler/docker/Dockerfile -t static-scanner:latest

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan: # DO NOT REMOVE OR MOVE THIS LINE
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: alerts-security-labs
      - security_scans:
          name: Security Scans
          context:
            - security-labs-snyk
      - build_crawler:
          name: Build Crawler Image
